videolan/libvlcsharp

LibVLCSharp/LibVLCSharp.csproj
LibVLCSharp/Shared/Core.cs
LibVLCSharp/Shared/MediaPlayer.cs
build-unity-android.ps1
build-unity-android.sh

This will be deployed on the Unity Store alongside an (opensource) unity plugin.

Initial Unity.Android setup

---

LibVLCSharp.Forms/LibVLCSharp.Forms.csproj
LibVLCSharp.WPF/LibVLCSharp.WPF.csproj
LibVLCSharp.sln
LibVLCSharp/LibVLCSharp.csproj
Samples/LibVLCSharp.WinForms.Sample/LibVLCSharp.WinForms.Sample.csproj
global.json

Also move msbuild.sdk.extras in global.json in solution root to manage its version more easily

Add VS2019 support for all projects

---

LibVLCSharp/Shared/Core.cs

Disable message box for errors when Windows cannot load some plugins (like on Windows XP).
- fixes # https://code.videolan.org/videolan/LibVLCSharp/issues/174
None
- Windows
None
Not applicable

Disable error dialogs when some plugins dlls fails to load

---

LibVLCSharp/Shared/Helpers/MarshalUtils.cs

Regression introduced in https://github.com/videolan/libvlcsharp/pull/66
`vasprintf` is the correct function to call on Apple platforms for libvlc logs marshalling.

Logging: Fix libvlc logging for Apple platforms

---

Directory.Build.props
LibVLCSharp/Shared/Core.cs
LibVLCSharp/Shared/Helpers/MarshalUtils.cs
LibVLCSharp/Shared/LibVLC.cs
LibVLCSharp/Shared/MediaPlayer.cs

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives/preprocessor-if#remarks

Build: Remove unnecessary defines

---

LibVLCSharp.Forms/Shared/MediaPlayerElement.xaml.cs
LibVLCSharp.Forms/Shared/PlaybackControls.xaml.cs
LibVLCSharp.Tests/MediaTests.cs
LibVLCSharp.Uno/SuspensionHelper.cs
LibVLCSharp/Shared/MediaPlayer.cs
LibVLCSharp/Shared/MediaPlayerElement/SeekBarManager.cs

Update mediaplayer fast/precise seeking support
Changed:
- SetTime
- SetPosition

Update mediaplayer fast precise support

---

LibVLCSharp/LibVLCSharp.csproj

Need to add some info to the LibVLC description texts as well, it's a bit light https://www.nuget.org/packages/VideoLAN.LibVLC.Windows/

packaging: update features info

---

LibVLCSharp.Uno/LibVLCSharp.Uno.csproj
LibVLCSharp/LibVLCSharp.csproj

Uniformization effort.
Not fixing any particular issue.
None
- Uno
- UWP

Uniform UWP/Uno platform packaging

---

global.json
scripts/linux-build.yml

More info at https://github.com/dotnet/sdk/issues/3770
Testing CI here.

Build: The WPF project doesn't build with .NET Core 3.1

---

LibVLCSharp/LibVLCSharp.csproj
LibVLCSharp/Shared/Core.cs
LibVLCSharp/Shared/MediaPlayer.cs
scripts/build-unity-android.ps1
scripts/build-unity-android.sh

LibVLCSharp for Unity code is only in master

Core: Remove unity code from 3.x branch

---

README.md
docs/home.md
docs/migrating_from_Vlc.DotNet.md

docs: initial Vlc.DotNet migration guide

---

buildsystem/linux-build.yml
buildsystem/mac-build.yml
buildsystem/windows-build.yml
src/global.json

Bumped .net SDK version
None
None
None
None
Not applicable
CI

Bumped .net sdk to 3.1.300 (Latest LTS)

---

samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.MediaElement.Sample.Android/MainActivity.cs
samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.MediaElement.Sample.Android/Resources/Resource.designer.cs
samples/Forms/LibVLCSharp.Forms.Sample.Android/Resources/Resource.designer.cs
samples/LibVLCSharp.Android.Sample/MainActivity.cs
samples/LibVLCSharp.UWP.Sample/MainPage.xaml
samples/LibVLCSharp.UWP.Sample/MainViewModel.cs
samples/LibVLCSharp.tvOS.Sample/ViewController.cs
src/LibVLCSharp.Forms/Platforms/Android/Platform.cs
src/LibVLCSharp.Forms/Platforms/Android/PowerManager.cs
src/LibVLCSharp.Forms/Platforms/Android/SystemUI.cs
src/LibVLCSharp.Forms/Platforms/Android/VideoViewRenderer.cs
src/LibVLCSharp.Forms/Platforms/Apple/Platform.cs
src/LibVLCSharp.Forms/Platforms/Apple/PowerManager.cs
src/LibVLCSharp.Forms/Platforms/Apple/VideoViewRenderer.cs
src/LibVLCSharp.Uno/VideoView.Android.cs
src/LibVLCSharp.Uno/VideoView.UWP.cs
src/LibVLCSharp.Uno/VideoView.iOS.cs
src/LibVLCSharp/Platforms/Android/LayoutChangeListener.cs
src/LibVLCSharp/Platforms/Android/VideoView.cs
src/LibVLCSharp/Platforms/Apple/VideoView.cs
src/LibVLCSharp/Platforms/UWP/InitializedEventArgs.cs
src/LibVLCSharp/Platforms/UWP/VideoView.cs
src/LibVLCSharp/Platforms/UWP/VideoViewBase.cs
src/LibVLCSharp/Platforms/UWP/VideoViewOfTInitializedEventArgs.cs
src/LibVLCSharp/Themes/Generic.xaml

Closes https://code.videolan.org/videolan/LibVLCSharp/-/issues/337
/cc @kakone

Platform Namespace cleanup

---

src/LibVLCSharp/Media.cs

thanks to @kakone 
need to backport to 3.x

media: fix async usage

---

src/LibVLCSharp/Structures/MediaStats.cs

https://github.com/videolan/vlc/commit/bdcc427549a47d50799319d751fabd64e5dbb5e8

media stats: add late frames info

---

samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement/MainPage.xaml
samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement/MainPage.xaml.cs
samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement/MainViewModel.cs
samples/Forms/LibVLCSharp.Forms.Sample/MainPage.xaml.cs
samples/Forms/LibVLCSharp.Forms.Sample/MainViewModel.cs
samples/LibVLCSharp.Android.Sample/LibVLCSharp.Android.Sample.csproj
samples/LibVLCSharp.Android.Sample/MainActivity.cs
samples/LibVLCSharp.FSharp.Sample/Program.fs
samples/LibVLCSharp.Mac.Sample/ViewController.cs
samples/LibVLCSharp.UWP.Sample/LibVLCSharp.UWP.Sample.csproj
samples/LibVLCSharp.UWP.Sample/MainViewModel.cs
samples/LibVLCSharp.WPF.Sample/Controls.xaml.cs
samples/LibVLCSharp.WPF.Sample/Example2.xaml.cs
samples/LibVLCSharp.WinForms.Sample/Form1.cs
samples/LibVLCSharp.iOS.Sample/LibVLCSharp.iOS.Sample.csproj
samples/LibVLCSharp.iOS.Sample/ViewController.cs
samples/LibVLCSharp.tvOS.Sample/ViewController.cs
src/LibVLCSharp.WinForms/VideoView.cs

https://github.com/videolan/libvlcsharp/commit/7fa00794b8ce6b1f84754085e625e920ffe60958 was necessary to prevent a crash given the samples changes of this branch.

add dispose to samples

---

README.md

Just adding some minimal code to the readme.

README: add sample code

---

buildsystem/linux-build.yml
buildsystem/mac-build.yml
buildsystem/windows-build.yml
samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement.Android/LibVLCSharp.Forms.Sample.MediaElement.Android.csproj
samples/Forms/LibVLCSharp.Forms.Sample.Android/LibVLCSharp.Forms.Sample.Android.csproj
samples/LibVLCSharp.Android.Sample/LibVLCSharp.Android.Sample.csproj
src/LibVLCSharp.Forms/Dispatcher.cs
src/LibVLCSharp.Forms/PlaybackControls.xaml.cs
src/LibVLCSharp/LibVLCSharp.csproj
src/global.json

just running CI for master branch

Fix ci build and update net sdk master

---

src/Directory.Build.props
src/LibVLCSharp.Android.AWindow/Directory.build.props
src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj
src/LibVLCSharp.Forms.Platforms.GTK/LibVLCSharp.Forms.Platforms.GTK.csproj
src/LibVLCSharp.Forms.Platforms.WPF/LibVLCSharp.Forms.Platforms.WPF.csproj
src/LibVLCSharp.Forms/LibVLCSharp.Forms.csproj
src/LibVLCSharp.GTK/LibVLCSharp.GTK.csproj
src/LibVLCSharp.Tests/LibVLCSharp.Tests.csproj
src/LibVLCSharp.Tests/LibVLCTests.cs
src/LibVLCSharp.Uno/LibVLCSharp.Uno.csproj
src/LibVLCSharp.WPF/LibVLCSharp.WPF.csproj
src/LibVLCSharp.WinForms/LibVLCSharp.WinForms.csproj
src/LibVLCSharp/LibVLCSharp.csproj

csproj: Simplify setup

---

samples/LibVLCSharp.Avalonia.Sample/App.xaml
samples/LibVLCSharp.Avalonia.Sample/App.xaml.cs
samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
samples/LibVLCSharp.Avalonia.Sample/Program.cs
src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj

LibVLCSharp.Avalonia: move to stable

---

samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
src/LibVLCSharp/Events/MediaPlayerEventManager.cs
src/LibVLCSharp/Helpers/MarshalExtensions.cs
src/LibVLCSharp/LibVLCEvents.cs
src/LibVLCSharp/MediaPlayer.cs
src/LibVLCSharp/Structures/Program.cs

Program api libvlc4

---

src/LibVLCSharp.Tests/EventManagerTests.cs
src/LibVLCSharp/Events/MediaEventManager.cs
src/LibVLCSharp/LibVLCEvents.cs
src/LibVLCSharp/Media.cs

to be rebased on master once https://github.com/videolan/libvlcsharp/pull/186 is merged

Remove media freed

---

src/LibVLCSharp/Structures/MediaTrack.cs

https://code.videolan.org/videolan/vlc-unity/-/issues/104
https://mailman.videolan.org/pipermail/vlc-devel/2021-April/143192.html

MediaTrackList: Fix crash in indexer binding code

---

samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement.Android/LibVLCSharp.Forms.Sample.MediaElement.Android.csproj
samples/Forms/LibVLCSharp.Forms.Sample.Android/LibVLCSharp.Forms.Sample.Android.csproj
samples/Forms/LibVLCSharp.Forms.Sample.GTK/LibVLCSharp.Forms.Sample.GTK.csproj
samples/Forms/LibVLCSharp.Forms.Sample.Mac/LibVLCSharp.Forms.Sample.Mac.csproj
samples/Forms/LibVLCSharp.Forms.Sample.Mac/packages.config
samples/Forms/LibVLCSharp.Forms.WPF.Sample/LibVLCSharp.Forms.Sample.WPF.csproj
samples/LibVLCSharp.Android.Sample/LibVLCSharp.Android.Sample.csproj
samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
samples/LibVLCSharp.FSharp.Sample/LibVLCSharp.FSharp.Sample.fsproj
samples/LibVLCSharp.GTK.Sample/LibVLCSharp.GTK.Sample.csproj
samples/LibVLCSharp.Mac.Sample/LibVLCSharp.Mac.Sample.csproj
samples/LibVLCSharp.Mac.Sample/packages.config
samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
samples/LibVLCSharp.UWP.Sample/LibVLCSharp.UWP.Sample.csproj
samples/LibVLCSharp.WPF.Sample/LibVLCSharp.WPF.Sample.csproj
samples/LibVLCSharp.WinForms.Sample/LibVLCSharp.WinForms.Sample.csproj
samples/LibVLCSharp.tvOS.Sample/LibVLCSharp.tvOS.Sample.csproj
samples/LibVLCSharp.tvOS.Sample/packages.config
samples/Uno/LibVLCSharp.Uno.Sample.UWP/LibVLCSharp.Uno.Sample.UWP.csproj
samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.UWP/Sample.MediaPlayerElement.UWP.csproj
src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj
src/LibVLCSharp.Tests/LibVLCSharp.Tests.csproj
src/LibVLCSharp.Tests/MediaTests.cs
src/LibVLCSharp.WPF/LibVLCSharp.WPF.csproj
src/LibVLCSharp.WinForms/LibVLCSharp.WinForms.csproj

Update deps for master

---

src/LibVLCSharp/Shared/Media.cs

close https://code.videolan.org/videolan/LibVLCSharp/-/issues/469

Media: Add Uri overload

---

src/LibVLCSharp.Forms/IOrientationHandler.cs
src/LibVLCSharp.Forms/Platforms/Android/OrientationHandler.cs
src/LibVLCSharp.Forms/Platforms/Apple/OrientationChangeListener.cs
src/LibVLCSharp.Forms/Platforms/Apple/OrientationHandler.cs
src/LibVLCSharp.Forms/PlaybackControls.xaml.cs
src/LibVLCSharp.Forms/README.md
src/LibVLCSharp.Forms/Resources/Strings.Designer.cs
src/LibVLCSharp.Forms/Resources/Strings.fr.resx
src/LibVLCSharp.Forms/Resources/Strings.resx
src/LibVLCSharp.Forms/SwipeToUnLockView.cs
src/LibVLCSharp.Forms/Themes/Generic.xaml

MediaElement XF: Add lock screen feature

---

README.md

Changed Trac to GitLab as bug tracker for the native code in the readme.
N/A
None
N/A
None
Not applicable
N/A

Update VLC bug tracker from Trac to GitLab

---

src/LibVLCSharp/Shared/MediaPlayer.cs

Add helper method SeekTo to mediaplayer.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/467
Added:
- void SeekTo(TimeSpan time)

mediaplayer: add helper SeekTo method

---

src/LibVLCSharp.Tests/LibVLCSharp.Tests.csproj

test project is using an old build which started getting tls issues, updating to latest libvlc.

tests: update libvlc build

---

docs/getting_started.md

Due to a quirk with how mouse events work in WPF, things such as context menus and mouse-click events can be tricky to work with - as seen with the `VideoView`.
This documentation change highlights this as well as adds a rather easy workaround to get those working as expected.
- [Mentioned Here](https://code.videolan.org/videolan/LibVLCSharp/-/issues/148)
None
- Core
- WPF
None
N/A
N/A - can be tested by following the steps added in this documentation commit.

Documentation for WPF context menu & mouse events

---

src/LibVLCSharp.WPF/User32Wrapper.cs
src/LibVLCSharp.WPF/VideoHwndHost.cs

Wpf win interop v4

---

src/LibVLCSharp.WPF/VideoView.cs

Fix https://code.videolan.org/videolan/LibVLCSharp/-/issues/537

WPF: check mp native reference during attach/detach of HWND

---

buildsystem/base-template.yml
samples/Forms/LibVLCSharp.Forms.Sample.GTK/LibVLCSharp.Forms.Sample.GTK.csproj
samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
samples/LibVLCSharp.CustomRendering.Direct3D11/LibVLCSharp.CustomRendering.Direct3D11.csproj
samples/LibVLCSharp.FSharp.Sample/LibVLCSharp.FSharp.Sample.fsproj
samples/LibVLCSharp.GTK.Sample/LibVLCSharp.GTK.Sample.csproj
samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
samples/LibVLCSharp.UWP.Sample/LibVLCSharp.UWP.Sample.csproj
samples/LibVLCSharp.WPF.Sample/LibVLCSharp.WPF.Sample.csproj
samples/LibVLCSharp.WinForms.Sample/LibVLCSharp.WinForms.Sample.csproj
src/global.json

On my computer, I am quite low on disk space, and downloading several versions of the same package, especially libvlc ones, makes things worse.
In this PR, I aligned the versions of the packages and updated the SDK version to 6.0.200
This is the 4.x version of PR #278

consolidate 4.x packages

---

buildsystem/base-template.yml
samples/Forms/LibVLCSharp.Forms.Sample.GTK/LibVLCSharp.Forms.Sample.GTK.csproj
samples/Forms/LibVLCSharp.Forms.WPF.Sample/LibVLCSharp.Forms.Sample.WPF.csproj
samples/LibVLCSharp.UWP.Sample/LibVLCSharp.UWP.Sample.csproj
samples/Uno/LibVLCSharp.Uno.Sample.UWP/LibVLCSharp.Uno.Sample.UWP.csproj
samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.UWP/Sample.MediaPlayerElement.UWP.csproj
src/global.json

On my computer, I am quite low on disk space, and downloading several versions of the same package, especially libvlc ones, makes things worse.
In this PR, I aligned the versions of the packages and updated the SDK version to 6.0.200

consolidate 3.x packages

---

samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
src/LibVLCSharp/LibVLCSharp.csproj

build: try workaround xamarin macios toolchain regression

---

buildsystem/azure-pipelines.yml
buildsystem/build.cake

Windows CI still failing because the GTK download link is 404

Update cake api

---

src/LibVLCSharp/LibVLC.cs

https://code.videolan.org/videolan/vlc/-/merge_requests/2843

uwp: no need to force the audio ouput anymore from v4

---

src/LibVLCSharp/Helpers/MarshalUtils.cs
src/LibVLCSharp/LibVLC.cs
src/LibVLCSharp/MediaPlayer.cs
src/LibVLCSharp/Structures/TimePoint.cs

mediaplayer: add new timer API

---

src/LibVLCSharp/Media.cs

https://code.videolan.org/videolan/vlc/-/commit/413239530a851c03e52a370f539dab90ac5b1807

media: update parsing flags value

---

src/LibVLCSharp/Media.cs

https://code.videolan.org/videolan/vlc/-/commit/90c01a3a9b77c336a5c06738687de1a51cd4510a

media: update MediaParsedStatus

---

src/LibVLCSharp.MAUI/AppHostBuilderExtensions.cs
src/LibVLCSharp.MAUI/Handlers/VideoViewHandler.cs
src/LibVLCSharp.MAUI/LibVLCSharp.MAUI.csproj

This allows classic Xforms style solutions with x-platform .csproj and multiple platform-specific .csproj files to add the libVLCsharp.Maui package as a dependency.
Added .net8 target framework and corresponding conditional compile sections to allow libVLCsharp.Maui package to be added and link to "generic" .net8 targeted Maui projects containing x-platform UI components.
- fixes #
None
- iOS
- Android
- WinUI
None
Not applicable

add .Net 8 core target framework to allow support adding package to non-shared-project structures
