videolan/libvlcsharp

- LibVLCSharp/Shared/EventManager.cs
- LibVLCSharp/Shared/VLCException.cs
It should set the `Message` property by calling the constructor with a message.
Otherwise `.ToString()` does not print any useful info.
Put it in a separate file.
> refactored VLCException

- LibVLCSharp.Tests/DialogTests.cs
- LibVLCSharp.Tests/EventManagerTests.cs
- LibVLCSharp.Tests/MediaPlayerTests.cs
- LibVLCSharp.Tests/MediaTests.cs
- LibVLCSharp.Tests/RendererDiscovererTests.cs
- LibVLCSharp/Shared/LibVLCEvents.cs
- LibVLCSharp/Shared/Media.cs
- LibVLCSharp/Shared/MediaPlayer.cs
- Aligns with other enum types
- Removes unneeded redundancy
> Move media enums outside the Media class

- scripts/mac-build.yml
This is (hopefully) a temporary change until https://developercommunity.visualstudio.com/content/problem/557330/macos-nuget-custom-sdk.html is resolved because that URL points to mono builds that change.
> CI: Download different mono build

- LibVLCSharp.WPF/VideoView.cs
This allows video overlaying elements inside XAML \<VideoView\> tag to be data bound to viewmodel's properties in MVVM scenarios.
> Add VideoView's DataContext passthrough to Foreground window

- LibVLCSharp/Shared/Helpers/MarshalUtils.cs
- LibVLCSharp/Shared/LibVLC.cs
ulong is not always correct for size_t marshaling. 
Use UIntPtr for P/Invoke and cast to uint or ulong depending on bitness.
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/217
None
None
Not applicable
Try running `_libVLC.RendererList.FirstOrDefault(r => r.Name.Equals("microdns_renderer"));` in release mode on device. Crashes in the `libvlc_renderer_discoverer_list_release` native call because of wrong count param.
With the fix, it works fine (release/debug/device/x86-sim). No public API change.
> Core: Fix size_t C# interop

- LibVLCSharp/Shared/Helpers/MarshalUtils.cs
- LibVLCSharp/Shared/Helpers/PlatformHelper.cs
- LibVLCSharp/Shared/LibVLC.cs
- Fix logging on all instances bug.
- Fix linux crash by allocating dynamically buffer size.
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/213
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/216
None
Try enabling/disabling logging on all supported platforms and devices and see if it works fine.
> Fix libvlc logs bugs

- LibVLCSharp.WPF/LibVLCSharp.WPF.csproj
- LibVLCSharp.WinForms/LibVLCSharp.WinForms.csproj
- Samples/LibVLCSharp.WinForms.Sample/LibVLCSharp.WinForms.Sample.csproj
I apologize for not updating the existing PR. I had so many problems trying to rebase. I no longer have issues building w/ MSBuild.Sdk.Extras 2.0..54. 
You can run the winforms sample by running ```dotnet run -f netcoreapp3.0``` from sample directory. 
Add support for .net core 3.0 winforms and wpf. Update winforms sample to support netcoreapp3.0. 
- fixes #140
None
New platform added
- netcoreapp3.0
None
Not applicable
> WinForms/WPF .NET Core 3 support for LibVLCSharp

- LibVLCSharp.Forms/Shared/PlaybackControls.xaml.cs
- LibVLCSharp/Shared/RendererDiscoverer.cs
As of libvlc 3, we can figure out the name internally so it makes sense to make that parameter optional. It is not an API breaking change. It is still possible to provide your own.
Moreover, mdns seems available on iOS and returns sometimes valid, sometimes invalid renderers.
The MediaElement now uses the new API which always uses only the bonjour protocol on Apple platforms.
- Incidentally fixes https://code.videolan.org/videolan/LibVLCSharp/issues/237
Changed:
- `RendererDiscoverer(LibVLC libVLC, string name)` => `RendererDiscoverer(LibVLC libVLC, string name = null)`
Try chromecasting on several platforms.
> RendererDiscoverer: Make renderer name optional

- LibVLCSharp/Shared/MediaPlayerElement/VolumeManager.cs
An assignment was incorrectly used instead of a comparison with the value.
The IDE was complaining. 😁
Other than that, I suppose that incorrect behavior could have been observed when setting `Enabled = false`
None
Core (all platforms)
None
Not applicable
Try calling Enabled with different values, I guess?
> Fixed flawed logic in VolumeManager

- LibVLCSharp.Uno/PlaybackControlsBase.cs
- LibVLCSharp/Shared/MediaPlayerElement/VolumeManager.cs
Currently, on Android, if I subscribe to the MediaPlayer.VolumeChanged event, the application crashes when the media player is stopped (the problem must come from libVLC or Xamarin).
This pull request removes the subscription to the MediaPlayer.VolumeChanged event. It's just a workaround, idealy, it shouldn't crash when the media player is stopped.
> VolumeChanged event bug workaround

- LibVLCSharp/Shared/LibVLC.cs
- LibVLCSharp/Shared/MediaPlayer.cs
We have seen several issues related to libvlc callbacks that were called while the .net GC has collected the methods.
This fixes those kind of issues in the following APIs:
- Video callbacks
- Audio callbacks
- Dialog callbacks
- fixes #275
None, all changes are internal
None
Not applicable
https://github.com/sergiocapozzi77/SetDialogsCrash
https://github.com/jeremyVignelles/libvlcsharp-samples/commit/1ed62bd769ea16860f161dbc12911dae88c278f0
> Fix collected callbacks

- LibVLCSharp/Shared/Core.cs
- Samples/LibVLCSharp.Android.Sample/Properties/AndroidManifest.xml
Fix LibVLC loading on Android API 17 and older by explicitly loading libc++_shared.so
This patch should be located in the InitializeAndroid method, but it doesn't work if it is there. Must look at generated code.
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/280
None
- Android
Try running the Android sample on a Android API 17 simulator.
> Fix libvlc loading on old android versions

- LibVLCSharp.WPF/VideoView.cs
- Samples/LibVLCSharp.WPF.Sample/Example1.xaml.cs
- Samples/LibVLCSharp.WPF.Sample/Example2.xaml.cs
Fix a leak with the foreground window when the VideoView is disposed
In VideoView.Dispose()
- close the foreground window
- dispose the PlayerHost
In the WPF samples
- dispose the VideoView when the window is closed
None
None
WPF
None
Not applicable
- Start the WPF sample with a memory profiler
- Open Example 1 and close the window
- Open Example 2 and close the window
- Take a memory snapshot
- Check that no instance of ForeroundWindow or VideoView have survived
> Fix a memory leak with the foreground window (WPF)

- LibVLCSharp/Shared/MediaPlayerElement/IDisplayInformation.cs
Unnecessary and breaks builds with older compilers (C#7 and under)
> MediaPlayerElement: Remove interface member modifier

- LibVLCSharp/Shared/Core.cs
This was partly fixed in https://github.com/videolan/libvlcsharp/pull/88 but not entirely, according to https://code.videolan.org/videolan/LibVLCSharp/issues/283. This commit should fix it for good.
Always load libcpp on Android regardless of Android version
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/283
None
- Android
> Core: Always load libcpp on Android regardless of Android version

- LibVLCSharp/Shared/Core.cs
- LibVLCSharp/Shared/Helpers/MarshalUtils.cs
Improve LibVLC loading error messages
A user could misuse the API in several ways:
- core.initialize is not called, libvlc is not installed.
- core.initialize is not called, libvlc is installed.
- core.initialize is called, libvlc is not installed.
These messages intend to help guide the user on which steps to take to initialize libvlc properly.
- fixes https://code.videolan.org/videolan/LibVLCSharp/issues/300
and probably a lot more.
None
> Core: Improve LibVLC loading error messages

- buildsystem/build.cake
- samples/Uno/LibVLCSharp.Uno.Sample.Droid/LibVLCSharp.Uno.Sample.Droid.csproj
- samples/Uno/LibVLCSharp.Uno.Sample.iOS/LibVLCSharp.Uno.Sample.iOS.csproj
- samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.Droid/Sample.MediaPlayerElement.Droid.csproj
- samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.iOS/Sample.MediaPlayerElement.iOS.csproj
- src/LibVLCSharp.Uno/LibVLCSharp.Uno.csproj
- src/LibVLCSharp.Uno/filtered.layout.resfiles
- src/LibVLCSharp.sln
Adds the LibVLCSharp project as an assembly reference instead of a project reference. With this change, the LibVLCSharp.Uno.pri file is correctly generated for the UWP platform.
`<Reference Include="$(SolutionDir)LibVLCSharp\bin\$(Configuration)\$(TargetFramework)\LibVLCSharp.dll" />`
Disadvantage : the NuGet package can't be automatically generated on build anymore (because the package reference to LibVLCSharp is missing). A new nupsec file must be created.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/294
None
> Fixes #294

- src/LibVLCSharp.Uno/PlaybackControlsBase.cs
- src/LibVLCSharp.Uno/Themes/PlaybackControls.xaml
- src/LibVLCSharp/Shared/MediaPlayerElement/AspectRatioManager.cs
- Corrects the SeekBarUnavailable state.
- Corrects the ZoomUnavailablity state.
- Updates the visibility of the playback controls after fade in / fade out (currently, only the opacity is modified).
- Prevent AspectRatio menu item from being unchecked
- Corrects FitScreen aspect ratio when the video track width and height are equals to 0 (perhaps it will fix [#270](https://code.videolan.org/videolan/LibVLCSharp/-/issues/270) but I'm not sure).
- Always keep the selected aspect ratio
- The IsSeekBarVisible property doesn't work on PlaybackControls, so the seek bar can't be hidden.
- The IsZoomButtonVisible property doesn't work
None
- UWP / Uno MediaPlayerElement
> Few corrections in Uno MediaPlayerElement

- README.md
The LGPL license is not very common in the dotnet world,
so people should check their assumptions and make sure they understand what it allows and doesn't allow.
> README: Add tldr legal link to LGPL license

- README.md
- buildsystem/azure-pipelines.yml
- buildsystem/build.cake
- buildsystem/windows-build.yml
- src/Directory.Build.props
Setup continuous delivery for the 8 LibVLCSharp nuget packages to feedz.
Only deploy for 3.x/master commits, if the build of all nugets has been successful. Versioning uses the current day and the build ID, as a pre-release package.
This will allow testing libvlcsharp 4/libvlc 4 more easily, and enable users to try it out.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/349
None
> CD: push LibVLCSharp.* nupkg to feedz

- src/LibVLCSharp.Tests/LibVLCAPICoverage.cs
- src/LibVLCSharp/MediaDiscoverer.cs
- src/LibVLCSharp/MediaPlayer.cs
Adapt test to include unused dllimport statements.
Removed 4 libvlc APIs not available anymore.
At the time of writing, there are 13 libvlc APIs left to implement for 100% libvlc coverage on libvlcsharp 4/libvlc 4:
```
libvlc_media_get_tracklist
libvlc_media_track_hold
libvlc_media_track_release
libvlc_media_tracklist_at
libvlc_media_tracklist_count
libvlc_media_tracklist_delete
libvlc_media_player_get_tracklist
libvlc_media_player_get_track_from_id
libvlc_media_player_get_selected_track
libvlc_media_player_select_track
libvlc_media_player_select_tracks
libvlc_media_player_select_tracks_by_ids
libvlc_video_set_output_callbacks
```
`libvlc_video_set_output_callbacks` has been implemented before, but needs some updating.
This doesn't test for:
- signature changes (params, return types, …
> Libvlc 4 coverage

- src/LibVLCSharp/Shared/Helpers/MarshalUtils.cs
Apple specific interop wasn't used for libvlc logs on mac netcore. Worked fine for mono/cocoa.
- None
- macOS
> Log interop: Fix netcore support for libvlc logs on macOS

- src/LibVLCSharp.Uno/VideoView.UWP.cs
- src/LibVLCSharp/Shared/IVideoControl.cs
Fix crash
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/364
None
> core ui: the IVideoControl is used outside of the MediaPlayerElement

- src/LibVLCSharp/Helpers/MarshalExtensions.cs
- src/LibVLCSharp/LibVLCSharp.csproj
- src/LibVLCSharp/StreamMediaInput.cs
By leveraging Span<byte> and unsafe construct, we can get rid of a Marshal.Copy that bothered me from the beginning of the implementation of StreamMediaInput.
This implementation should give better performances around media input callback, and use less ram, but I didn't take time to benchmark.
Note : This PR is on top of #154 because I needed to build the projects... Feel free to rebase after #154 is merged
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/345
None
- netstandard2.1
- Android
- Apple
(looks weird to me that the mono projects build with that change, but either they did, or I fail to build them properly. Will adapt depending on the CI result)
None
Not applicable
Try using the StreamMediaInput and see if it still work.
> Avoid a copy in StreamMediaInput on modern platform

- src/LibVLCSharp/LibVLCSharp.csproj
- src/LibVLCSharp/Shared/Helpers/MarshalExtensions.cs
- src/LibVLCSharp/Shared/StreamMediaInput.cs
backporting https://github.com/videolan/libvlcsharp/pull/155 to 3.x branch
> Avoid a copy in StreamMediaInput on modern platforms

- samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement/MainViewModel.cs
- samples/Forms/LibVLCSharp.Forms.Sample/MainViewModel.cs
- samples/LibVLCSharp.Android.Sample/MainActivity.cs
- samples/LibVLCSharp.FSharp.Sample/Program.fs
- samples/LibVLCSharp.GTK.Sample/Program.cs
- samples/LibVLCSharp.Mac.Sample/ViewController.cs
- samples/LibVLCSharp.NetCore.Sample/Program.cs
- samples/LibVLCSharp.UWP.Sample/MainViewModel.cs
- samples/LibVLCSharp.WPF.Sample/Controls.xaml.cs
- samples/LibVLCSharp.Windows.Net40.Sample/Program.cs
- samples/LibVLCSharp.iOS.Sample/ViewController.cs
- samples/LibVLCSharp.tvOS.Sample/ViewController.cs
- samples/Uno/LibVLCSharp.Uno.Sample.Shared/MainViewModel.cs
- samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.Shared/MainViewModel.cs
- src/LibVLCSharp/Shared/LibVLC.cs
The goal is have it enabled by default (?).
So many times people are not aware of the --verbose option, because exposing only an array of strings
means you need to go check the vlc cli page for information.
Having an enum explicitly for this makes it discoverable from the VS intellisense. It may be good to have it enabled by default.
- None, but in most I have to point to docs on how to enable logging.
Added:
- LibVLCLog enum. Probably to be enabled by default.
> core: Add logging helper to libvlc constructor

- samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
- src/LibVLCSharp/Shared/Media.cs
- src/LibVLCSharp/Shared/MediaInput.cs
- src/LibVLCSharp/Shared/StreamMediaInput.cs
These are the same changes as https://github.com/ZeBobo5/Vlc.DotNet/pull/648
Streams where CanSeek is false should not be declared as seekable in libvlc.
Also increased the buffer size to match the libvlc buffer size.
None opened on LVS, but see https://github.com/ZeBobo5/Vlc.DotNet/issues/647
Added:
- bool MediaInput.CanSeek { get; protected set; } // Defaults to true, must be set to false in subclasses constructor.
Changed:
- Native.LibVLCMediaNewCallbacks now has a nullable parameter for seekCb
Will not attempt to call Seek if the `Stream` is not seekable in `StreamMediaInput`. LibVLC will now understand that the stream is not seekable and will show appropriate log messages.
Not applicable
Didn't have time to push it to a repo, sorry:
```cs
Core.Initialize(); …
```
> Declared non-seekable streams as non-seekable in callback input

- docs/linux-setup.md
The documentation was referring to ubuntu 18.10. Things have changed since then and mono/msbuild is not needed anymore (`dotnet build` works fine)
None
Not applicable
Not applicable
Not applicable
Not applicable
Tried to install the Avalonia project on linux, had issues with missing `libX11.so`. Installing gtk-sharp installs a `/lib/libX11.so`, but we don't need such a heavy thing, and `libx11-dev` is enough to make it work.
> Updated linux documentation

- src/LibVLCSharp.WPF/ForegroundWindow.xaml.cs
1. The WPF window loaded event can fire multiple times, therefore a check has been added to ensure this is now only executed once as otherwise there is the risk of attempting to show a window more than once (which is illegal in WPF and throws an exception)
2. When the WPF window is closing, event handlers are now unsubscribed
Exceptions thrown by WPF when docking/undocking/showing/hiding a window.
None
WPF
No exceptions thrown when docking/undocking window.
Not applicable
https://code.videolan.org/videolan/LibVLCSharp/-/issues/384
> Wpf eventhandler fixes

- buildsystem/build.cake
The CD modifies version suffixes, override if there is an existing one,
So that CD works even for current pre-release packages.
> CD: Fix continuous delivery script for existing pre-release nugets

- src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj
The new Avalonia version includes a fix for https://code.videolan.org/videolan/LibVLCSharp/-/issues/458
> Avalonia: Bump version reference

- src/LibVLCSharp/Shared/MediaPlayer.cs
- src/LibVLCSharp/Shared/MediaPlayerElement/AspectRatioManager.cs
- src/LibVLCSharp/Shared/MediaPlayerElement/StateManager.cs
Related to https://github.com/videolan/libvlcsharp/pull/205
> Core: Fix Media leaks

- src/LibVLCSharp/Shared/Core/Core.cs
`Assembly.Location` is deprecated and returns `string.Empty` in .NET 5 and later when using Single file self contained apps. 
See https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#api-incompatibility
- fix https://code.videolan.org/videolan/LibVLCSharp/-/issues/470
None
Haven't tried Linux/macOS
None
Not applicable
Checked that this fixes running a self contained single app net5 app sample on Windows.
> Core: Fix resolving libvlc location for single file self contained apps

- src/global.json
Sometimes when switching computers I end up with a slightly newer or older, but still compatible, .NET SDK version. Just pushing this small local patch for friendlier dev XP.
> build: allow a range of compatible minor SDK versions

- samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement.iOS/AppDelegate.cs
- src/LibVLCSharp.Forms/Platforms/Android/OrientationHandler.cs
- src/LibVLCSharp.Forms/Platforms/Apple/OrientationChangeListener.cs
- src/LibVLCSharp.Forms/Platforms/Apple/OrientationHandler.cs
- src/LibVLCSharp.Forms/README.md
- src/LibVLCSharp.Forms/Shared/IOrientationHandler.cs
- src/LibVLCSharp.Forms/Shared/MediaPlayerElement.xaml.cs
- src/LibVLCSharp.Forms/Shared/PlaybackControls.xaml.cs
- src/LibVLCSharp.Forms/Shared/Resources/Strings.Designer.cs
- src/LibVLCSharp.Forms/Shared/Resources/Strings.fr.resx
- src/LibVLCSharp.Forms/Shared/Resources/Strings.resx
- src/LibVLCSharp.Forms/Shared/SwipeToUnLockView.cs
- src/LibVLCSharp.Forms/Shared/Themes/Generic.xaml
Added Lockscreen feature to the LibVLCSharp.Forms project. When user clicks on the lock button, PlayBack Controls are hidden, SeekBar is in read-only mode and the device's orientation is locked. 
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/180
Added:
- SwipeToUnLockView : a custom view to unlock screen
- IOrientationHandler, OrientationHandler : Dependency to lock or unlock device's orientation.
Updated:
- MediaPlayerElement.xaml.cs
- Generic.xaml, Generic.xaml.cs
- MediaPlayerElement.xaml.cs
- Strings.resx
- iOS
- Android
Before:
Andoid          |  iOS
:-------------------------:|:-------------------------:
Before:
Andoid          |  iOS
:-------------------------:|:-------------------------:
On iOS, you have to override the GetSupportedInterfaceOrientations method in …
> XF: Lockscreen feature Added - Fixes #180

- buildsystem/windows-build.yml
Fixes regularly failing Windows CI
```
gtksharp v2.12.45 [Approved]
gtksharp package files install completed. Performing other installation steps.
Attempt to get headers for https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi failed.
The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi'. Exception calling "GetResponse" with "0" argument(s): "The remote server returned an error: (500) Internal Server Error."
Downloading gtksharp 
from 'https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi'
ERROR: The remote file either doesn't exist, is unauthorized, or is forbidden for url 'https://dl.xamarin.com/GTKforWindows/Windows/gtk-sharp-2.12.45.msi'. Exception calling …
```
> CI: Fix recurring chocolatey CDN failures

- src/LibVLCSharp.Forms/Shared/PlaybackControls.xaml.cs
- src/LibVLCSharp.Forms/Shared/Themes/Generic.xaml
Add IsLockButtonVisible and IsTracksButtonVisible properties which allow to hide or show the LockButton and the TracksButton.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/494
None
- iOS
- Android
None
> MediaElement XF: Fixes customization regression

- src/LibVLCSharp.Forms/Shared/Themes/Generic.xaml
Fixes Trackselection layout issue on mkv files with many tracks.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/497
Changed:
- Generic.xaml
None
- iOS
- Android
None
Before|  After
:-------------------------:|:-------------------------:
> MediaElement XF: Tracks Selection too much space fixed - Fixes #497

- docs/made_with_libvlcsharp.md
Added mention of KlingonWin10WPF to the made_with_libvlcsharp file.   This is an unofficial remake of the Executable of the FMV game portion of Star Trek: Klingon
Added a mention to a project made with libvlcsharp and WPF
NA - Documenting
- fixes #
None
Added:
- Mention of a project that utilizes this software.
-->
None
None
None
Not applicable
- [X ] Rebased on top of the target branch at time of PR
- [X ] Changes adhere to coding standard
> Added mention of KlingonWin10WPF to made_with_libvlcsharp.md

- src/LibVLCSharp/Shared/Core/Constants.cs
**Breaking change**
Since https://github.com/videolan/vlckit/commit/9e86882eca8ae209f5c0b29855c46e5ba4f6bd48, the vlckit project changed its packaging strategy by using the newer `xcframework` and retiring the XCode `DynamicMobileVLCKit` target that the LibVLC.iOS NuGet was using. For the record, the actual `MobileVLCKit` are still available and can be retrieved and used outside of the `xcframework` shell.
This change was motivated by adding support to M1 Macs and ARM64 simulators.
Well, shipping a new LibVLC iOS build on NuGet requires small but breaking changes
- [LibVLC iOS packaging changes](https://github.com/mfkl/libvlc-nuget/commit/634111ebd70e040c7c692e17362dbed1def68229).
- This PR, changing LibVLCSharp DLLImport section used in linking the final consumer app.
I have tested that …
> tvOS: packaging changes following upstream updates

- src/LibVLCSharp/Shared/Media.cs
On Windows, when using `FromPath` in the `Media` constructor, we want to rewrite internally the forward slashes into backslashes, like explorer.exe does, before feeding the path to LibVLC.
This does not affect the `FromLocation`/`Uri` constructors.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/517
No real important breaking change. If the user was doing it already on their side, this does not change the behavior.
If they were not and catching an exception, well, no more exception I guess.
- Windows
> media: rewrite slashes for windows

- src/LibVLCSharp/Shared/Internal.cs
- src/LibVLCSharp/Shared/Media.cs
When a user provides an incorrect MRL to create a media, the native function will return null and we will throw with a generic message. The exception message is cryptic in case of Media, so clarify it.
- None but mentioned in https://code.videolan.org/videolan/LibVLCSharp/-/issues/517 and discord.
None
> media: clarify error message if native media constructor fails

- src/LibVLCSharp/Platforms/Apple/VideoView.cs
Avoid crashing if the mediaplayer gets disposed before the view is detached
Fix https://code.videolan.org/videolan/LibVLCSharp/-/issues/520
The WinForms view has a similar check.
- fixes https://code.videolan.org/videolan/LibVLCSharp/-/issues/520
None
- iOS
> iOS: Add additional lifetime check

- src/LibVLCSharp.WPF/ForegroundWindow.cs
For whatever reason, the _bckgnd.LayoutUpdated event only fires inside of a debugger. So lets use the _wndhost.LocationChanged instead. I tested a few cases and everything seems to work fine now.
- fixes #523
None
- WPF
The WPF VideoView overlay no longer magically floats around somewhere on the screen
Before
After
Run LibVlcSharp WPF sample outside of the debugger and move the main window around the screen
- [x ] Rebased on top of the target branch at time of PR
- [x ] Changes adhere to coding standard
> Fixed WPF VideoView foreground window position bug

- src/LibVLCSharp.WPF/VideoView.cs
Used `IntPtr.Zero` to compare value of type `IntPtr` instead of `null`
net6.0 warns that this is always false...
None
-WPF
None, except for cases where this should already be crashing
Not applicable
Build
> Fixed `null` check instead of IntPtr.Zero

- src/LibVLCSharp.WPF/LibVLCSharp.WPF.csproj
- src/LibVLCSharp.WPF/Themes/Generic.xaml
- src/LibVLCSharp.WPF/User32Wrapper.cs
- src/LibVLCSharp.WPF/VideoHwndHost.cs
- src/LibVLCSharp.WPF/VideoView.cs
- Remove WinFormsHost from the WPF and create a win32 window and pass it to the MediaPlayer by taking advantage of HwndHost (https://docs.microsoft.com/en-us/dotnet/desktop/wpf/advanced/walkthrough-hosting-a-win32-control-in-wpf)
- Hide this HwndHost when MediaPlayer stopped to don't see the win32's window background and see WPF window background.
- WPF
> remove winform host from wpf project

- src/LibVLCSharp/Structures/MediaTrack.cs
See https://code.videolan.org/videolan/vlc/-/commit/635ecd1f2b52f976b47b81b6433eec1328d2e880
"All libvlc deprecated functions/members will be removed before VLC 4.0
freeze." 
But the freeze has not happened yet, so we need to keep this working.
> mediatrack: Use old Id if new StrId API is not used

- src/LibVLCSharp.WPF/User32Wrapper.cs
- src/LibVLCSharp.WPF/VideoHwndHost.cs
Fix Win32 interop in LibVLCSharp.WPF.
- No issue created.
None
- WPF
Came across this unrelated issue while debugging https://code.videolan.org/videolan/LibVLCSharp/-/issues/535
> Wpf win interop

- src/LibVLCSharp/LibVLCSharp.csproj
We are already using .NET 6, and the CI started complaining recently anyway (cross-build mono issue, probably).
```
D:\a\1\s\src\LibVLCSharp\obj\Release\net6.0-macos\LibVLCSharp.GlobalUsings.g.cs(2,1): error CS8773: Feature 'global using directive' is not available in C# 9.0. Please use language version 10.0 or greater. [D:\a\1\s\src\LibVLCSharp\LibVLCSharp.csproj]
```
> build: workaround temporary xamarin apple toolchain regression

- README.md
- docs/best_practices.md
- docs/getting_started.md
- docs/how_do_I_do_X.md
- docs/migrating_from_Vlc.DotNet.md
- samples/Forms/LibVLCSharp.Forms.MediaElement/LibVLCSharp.Forms.Sample.MediaElement/MainViewModel.cs
- samples/Forms/LibVLCSharp.Forms.Sample/MainViewModel.cs
- samples/LibVLCSharp.Android.Sample/MainActivity.cs
- samples/LibVLCSharp.Avalonia.Sample/App.xaml.cs
- samples/LibVLCSharp.FSharp.Sample/Program.fs
- samples/LibVLCSharp.GTK.Sample/Program.cs
- samples/LibVLCSharp.Mac.Sample/ViewController.cs
- samples/LibVLCSharp.NetCore.Sample/Program.cs
- samples/LibVLCSharp.UWP.Sample/App.xaml.cs
- samples/LibVLCSharp.WPF.Sample/App.xaml.cs
- samples/LibVLCSharp.Windows.Net40.Sample/Program.cs
- samples/Uno/LibVLCSharp.Uno.Sample.Shared/App.xaml.cs
- samples/Uno/Sample.MediaPlayerElement/Sample.MediaPlayerElement.Shared/App.xaml.cs
- src/LibVLCSharp.Tests/BaseSetup.cs
- src/LibVLCSharp.Tests/RendererDiscovererTests.cs
- src/LibVLCSharp/Shared/Core/Core.Android.cs
- src/LibVLCSharp/Shared/Core/Core.Apple.cs
- src/LibVLCSharp/Shared/Core/Core.Desktop.cs
- src/LibVLCSharp/Shared/Core/Core.UWP.cs
- src/LibVLCSharp/Shared/Core/Core.cs
- src/LibVLCSharp/Shared/Helpers/MarshalUtils.cs
- src/LibVLCSharp/Shared/Internal.cs
- src/LibVLCSharp/Shared/LibVLC.cs
Just creating this draft while I think more about it.
It should be documented that:
- if you need a custom location for libvlc, implicit loading won't guess the path for you, you need to call Core.Initialize() yourself with the custom path.
- it should be documented that the first `new LibVLC` can appear slower. That is because the same code now also loads libvlc on first time, while before it was just a regular constructor. Link to guidance to make libvlc load faster (plugins.dat, plugin cherry picking). If still too slow or not acceptable, load libvlc yourself by calling Core.Initialize() _way before_ you call `new LibVLC`.
- No lock is needed because only LibVLC and Equalizer could be created from multiple threads with the `Loaded` value potentially not up to date.
- You don't want to …
> Make Core.Initialize implicit

- samples/Forms/LibVLCSharp.Forms.Sample.GTK/LibVLCSharp.Forms.Sample.GTK.csproj
- samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
- samples/LibVLCSharp.CustomRendering.Direct3D11/LibVLCSharp.CustomRendering.Direct3D11.csproj
- samples/LibVLCSharp.Eto.Sample/LibVLCSharp.Eto.Sample.csproj
- samples/LibVLCSharp.GTK.Sample/LibVLCSharp.GTK.Sample.csproj
- samples/LibVLCSharp.NetCore.Sample/LibVLCSharp.NetCore.Sample.csproj
- samples/LibVLCSharp.WPF.Sample/LibVLCSharp.WPF.Sample.csproj
- samples/LibVLCSharp.WinForms.Sample/LibVLCSharp.WinForms.Sample.csproj
- samples/LibVLCSharp.Windows.Net45.Sample/LibVLCSharp.Windows.Net45.Sample.csproj
- src/LibVLCSharp.Tests/DialogTests.cs
- src/LibVLCSharp.Tests/LibVLCSharp.Tests.csproj
- src/LibVLCSharp.Tests/LibVLCTests.cs
- src/LibVLCSharp/LibVLC.cs
Updating to match https://code.videolan.org/videolan/vlc/-/commit/211baa3ffee2380ea8adba35f164a3ecd11bc69c.
To able to test:
- https://code.videolan.org/videolan/vlc/-/merge_requests/1864 needs to be merged.
- the nightly build needs to be fixed (e.g. libvlcpp updated to match new API) so we can easily try from VS.
- might want to add a unit test.
> dialog: split error callback

- src/LibVLCSharp/Events/MediaPlayerEventManager.cs
- src/LibVLCSharp/LibVLCEvents.cs
- src/LibVLCSharp/MediaPlayer.cs
The event is not currently firing, apparently something is incorrect on our side.
> mediaplayer: Add record binding

- samples/Forms/LibVLCSharp.Forms.Sample.Mac/LibVLCSharp.Forms.Sample.Mac.csproj
- src/LibVLCSharp.Forms/LibVLCSharp.Forms.csproj
- src/LibVLCSharp/LibVLCSharp.csproj
to revert next month when new VS build is shipped to the CI agents https://developercommunity.visualstudio.com/t/XamarinMac-binaries-are-missing-in-173/10164443
> CI: workaround VS 17.3.5 bug for missing xamarin.mac binaries

- buildsystem/windows-build.yml
Not great but the original download link is 404.
gtk-sharp 2.x won't be receiving any update anyway. 
Will fix the CI for now, happy to revert when the original link is fixed (winget, chocolatey, etc all failing as they rely on it too).
> CI: update gtk msi download url

- docs/linux-setup.md
- src/LibVLCSharp/Shared/Core/Constants.cs
- src/LibVLCSharp/Shared/Core/Core.Desktop.cs
- src/LibVLCSharp/Shared/LibVLC.cs
Removed x11 dependency / rework linux init to prevent errors when x11 is not used (e.g. on Wayland only environments)
- fixes #596
None
- Linux
None
Not applicable
- Run the default media player example on a Wayland only system
- Use the code from the updated documentation to run the default media player example on an X11 system
> 596 - removed x11 dependency and updated documentation

- src/LibVLCSharp.WPF/ForegroundWindow.cs
prevent to disappear video view's foreground window when host window closing canceled
- fixes #
None
- WPF
None
Not applicable
> Prevent disappear foreground window when closing canceled.

- src/LibVLCSharp.Tests/LibVLCAPICoverage.cs
- src/LibVLCSharp/Shared/LibVLC.cs
add libvlc clock binding. it could be useful for audio callbacks implementations 
- fixes https://github.com/mfkl/libvlcsharp-samples/issues/206
Added:
- long Clock { get; } 
> libvlc: add libvlc clock binding

- src/Directory.Build.props
- src/LibVLCSharp/Core/Constants.cs
- src/LibVLCSharp/Core/Core.Unity.cs
- src/LibVLCSharp/Helpers/PlatformHelper.cs
These changes are changing the Constants and path for plugins when building for `/p:UNITY=true`. In the case of iOS, a `/p:UNITY_IOS=true` will be necessary to build the libVLCSharp assembly with the correct path constant for referencing the frameworks.
Note that `SetPluginPath` must be available . 
- Unity (iOS and macOS)
None
Not applicable
Use `buildsystem/build-unity.sh` to compile, and potentially add `/p:UNITY_IOS=true` to test the iOS part.
Unfortunately, testing that everything works correctly is a bit more tedious and require first some changes in thre videolan/vlc-unity project.
I'll update the MR with the adequate steps when the Unity parts are merged.
> Add support for iOS and MacOS for the Unity support

- src/LibVLCSharp/Platforms/Windows/VideoViewBase.cs
This PR adds a `Clear` method to the UWP/WinUI `VideoViewBase` that can be used to clear the underlying `SwapChain` to restore the original visual appearance.
This is needed as currently the D3D11 vout retains the last rendered frame after the playback is completed. While in many scenarios this is desirable, an alternative is still needed.
Additionally, this changes the SwapChain's `AlphaMode` from `Unspecified` to `Premultiplied`, so that `Clear` actually turns the VideoView actually transparent, and not black. (This is needed in my scenario and the initial VideoView is actually transparent and not black--let me know if this work for you too or we can find a different solution)
Added:
- void VideoViewBase.Clear()
- UWP
`SwapChain.AlphaMode` was changed, but by looking at …
> Added Clear method, support for alpha

- samples/LibVLCSharp.Avalonia.Sample/App.xaml
- samples/LibVLCSharp.Avalonia.Sample/App.xaml.cs
- samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
- samples/LibVLCSharp.Avalonia.Sample/ViewLocator.cs
- src/LibVLCSharp.Avalonia/LibVLCSharp.Avalonia.csproj
Update project LibVLCSharp.Avalonia to Avalonia 11.04
Due to the difference between the 10 and 11 versions of Avalonia, it was impossible to use the current version LibVLCSharp in 11 Avalonia
Update Package Version:
- Avalonia 0.10.7 => 11.0.4
- Avalonia.Desktop 0.10.14 => 11.0.4
- Avalonia.ReactiveUI 0.10.14 => 11.0.4
Adding new Package:
- Avalonia.Themes.Fluent 11.0.4 => LibVLCSharp.Avalonia.Sample
Changed in LibVLCSharp.Avalonia.Sample:
- public IControl Build(object data) =>public Control Build(object data) // Because in version 11 interface IControl was removed
-  `<StyleInclude Source="resm:Avalonia.Themes.Default.DefaultTheme.xaml?assembly=Avalonia.Themes.Default"/><StyleInclude Source="resm:Avalonia.Themes.Default.Accents.BaseLight.xaml?assembly=Avalonia.Themes.Default"/>` => …
> Update to Avalonia 11

- src/LibVLCSharp.WPF/ForegroundWindow.cs
- src/LibVLCSharp.WPF/README.md
Platform: WPF
Topic: Airspace issue and the `ForegroundWindow `workaround
`ForegroundWindow` now supports _scaled video host_. The sizing and scaling `ForegroundWindow` had to be fixed.
_Scaled video host_ means that a scale transformation has been applied to the `VideoView` or one of its ancestors up to the containing window. This is also the case when the WPF `Viewbox` is used.
We currently have two use cases for this fix: 
1. In our business WPF application, we apply a general scale transform to the root of the main window to scale up/down the UI. This is used to compensate potentially wrong DPI settings (Windows), but also to offer the user the possibility to choose a comfortable "zoom level" to work with, just like in modern web browsers.
2. We have multiple IP cameras and we want to …
> WPF ForegroundWindow: Support scaled video host

- samples/LibVLCSharp.Avalonia.Sample/ViewModels/MainWindowViewModel.cs
- samples/LibVLCSharp.Avalonia.Sample/Views/MainWindow.xaml
- samples/LibVLCSharp.Avalonia.Sample/Views/MainWindow.xaml.cs
- samples/LibVLCSharp.Avalonia.Sample/Views/VideoPlayer.axaml
- samples/LibVLCSharp.Avalonia.Sample/Views/VideoPlayer.axaml.cs
- src/LibVLCSharp.Avalonia/VideoView.cs
In `VideoView` `MediaPlayer` handle was not properly assigned when using it in windows child component (eg. user control).
This caused MediaPlayer to popout to separate window. 
Added Initialized event handler that calls `Attach()` when control is initialized. 
Removed unnecessary Attach call from  `CreateNativeControlCore`. 
Updated **Avalonia.Sample** so that VideoView is displayed through user control and added play and stop buttons.
- fixes #525
None
- Avalonia
- Avalonia VideoView works properly in child controls
None
Not applicable
- Tested using Avalonia sample with windows desktop environment
> Avalonia VideoView fix

- samples/LibVLCSharp.Avalonia.Sample/Views/VideoPlayer.axaml
- samples/LibVLCSharp.Avalonia.Sample/Views/VideoPlayer.axaml.cs
- src/LibVLCSharp.Avalonia/VideoView.cs
Allow content to be placed to **VideoView** so that it renders it on top of the media player. 
- Created bindable **Content** property for **VideoView**.
- When content is assigned or **VideoView** is attached to visual tree, tries to create a new transparent overlay window that is placed on top of the **VideoView**.
- Content is binded to windows content property.
- Uses **VideoView** Content and Bound property changed events to update overlay position.
Updated sample.
Solution is based on this PR: https://github.com/videolan/libvlcsharp/pull/294
- fixes #408
Added:
- object VideoView.Content { get; set; } //Bindable Property
- Avalonia
If user places control inside VideoView it will be shown top of the video.
- Tested with Windows 11
> Avalonia: Child content support for VideoView

- buildsystem/build.cake
- src/LibVLCSharp.Android.AWindowModern/LibVLCSharp.Android.AWindowModern.csproj
- src/LibVLCSharp/LibVLCSharp.csproj
because PrivateAssets is broken on net6-android and newer toolchains.
> Android: Ship new Android binding to NuGet

- samples/LibVLCSharp.UWP.Sample/Package.appxmanifest
Add the capabilities that a regular UWP app using libvlcsharp can use. This is a better reference than the old vlc-winrt repository.
See the list of capabilities available: https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions#capabilities-for-accessing-other-locations
- UWP
> Uwp capabilities

- buildsystem/base-template.yml
since we don't build samples on mac ci anymore
> mac ci: remove unecessary SDK install

- src/LibVLCSharp.Avalonia/VideoView.cs
Adds an event handler for `VideoView.VisualRoot.LayoutUpdated `in `InitializeNativeOverlay()`.
Remove event handler for `BoundsProperty.Changed` as it's no longer needed.
Adds to the guard clause in `UpdateOverlayPosition()` so LayoutUpdated doesn't pelt a IsVisible = false VideoView with updates; Layout is updated on being made visible.
[Fixes 645](https://code.videolan.org/videolan/LibVLCSharp/-/issues/645)
None
- Avalonia Desktop
VideoView Content now moves correctly when being shifted by grid splitters.
All testing was performed on Manjaro Linux.
- Tested with and without video playback.
- Tested behavior while VideoView.IsVisible = false.
- Tested changing VideoView.Content.
The tests where performed using [this](https://code.videolan.org/Odalith/vlctest/-/tree/master?ref_type=heads) …
> Fix Avalonia VideoView failing to update Content position when shifted.

- samples/LibVLCSharp.MAUI.Sample/AppShell.xaml
- samples/LibVLCSharp.MAUI.Sample/LibVLCSharp.MAUI.Sample.csproj
- samples/LibVLCSharp.MAUI.Sample/MainPage.xaml
- samples/LibVLCSharp.MAUI.Sample/MainPage.xaml.cs
- samples/LibVLCSharp.MAUI.Sample/MainViewModel.cs
- samples/LibVLCSharp.MAUI.Sample/Properties/launchSettings.json
- samples/MAUI/LibVLCSharp.MAUI.Sample.MediaElement/LibVLCSharp.MAUI.Sample.MediaElement.csproj
- samples/MAUI/LibVLCSharp.MAUI.Sample.MediaElement/MainPage.xaml
- samples/MAUI/LibVLCSharp.MAUI.Sample.MediaElement/MainPage.xaml.cs
- samples/MAUI/LibVLCSharp.MAUI.Sample.MediaElement/MainViewModel.cs
- samples/MAUI/LibVLCSharp.MAUI.Sample.MediaElement/Properties/launchSettings.json
- src/LibVLCSharp.MAUI/Handlers/VideoViewHandler.cs
- src/LibVLCSharp.MAUI/LibVLCSharp.MAUI.csproj
- src/LibVLCSharp/Platforms/Windows/VideoViewBase.cs
- src/LibVLCSharp/Themes/Generic.xaml
Getting lots of these
```
DEP0900: Failed to unregister application "49861f9e-48d3-45c0-b6a8-f591ad6d2010_1.0.0.1_x64__9zz4h110yvjzm". [0x80073CFA] 
```
Unsure why. Impossible to uninstall existing appx that match this app ID.
On 3.x, on WinUI, the `LibVLC` object is built using string parameters retrieved from an initialized VideoView (see the plan WinUI sample code). Will have to re-work the code to handle this in the MAUI sample for WinUI support.
> Maui winui

- samples/LibVLCSharp.Avalonia.Sample/LibVLCSharp.Avalonia.Sample.csproj
Bumped avalonia sample to use avalonia 11.2.5 and target net8
Just modernized the avalonia sample project a bit.
None
- Windows
- OSx
- Linux
None
Not applicable
run the sample and see big buck bunny. 
I cannot test on OSx myself so that may be a small risk. 
- [X ] Rebased on top of the target branch at time of PR
- [ X] Changes adhere to coding standard
> avalonia sample target net8 and bump to avalonia 11.2.5

- src/LibVLCSharp.WPF/User32Wrapper.cs
- src/LibVLCSharp.WPF/VideoHwndHost.cs
Add WS_CLIPCHILDREN window style to fix white window background
fixes #[#555](https://code.videolan.org/videolan/LibVLCSharp/-/issues/555)
None
Added:
- WS_CLIPCHILDREN Window32Style
Changed:
- CreateWindowEx in HandleRef BuildWindowCore(HandleRef hwndParent)
- Windows WPF
The VideoView control's background is now stable
I used a personal project that uses LibVLCSharp.Wpf to test my changes. 
- [ x] Rebased on top of the target branch at time of PR
- [ x] Changes adhere to coding standard
> Add WS_CLIPCHILDREN window style to fix white window background

- src/LibVLCSharp.Mac.slnx
not included anymore on CI agents and deprecated for years anyway. Windows still builds it.
> CI: remove GTK from macOS builds
